//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationSystemKZ_Azure.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TuitionFee
    {
        public int InvoiceId { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime DateTime { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM/yyyy}")]
        public System.DateTime FeePeriod { get; set; }
        public int StudentId { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
